services:
  bot-trading:
    build: .
    container_name: bot_trading_prod
    network_mode: 'host' # <--- Usamos la red de la máquina directamente
    restart: always
    environment:
      - DB_HOST=localhost # En modo host, la DB está en "localhost"
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    deploy:
      resources:
        limits:
          memory: 256M
