services:
  bot-trading:
    build: .
    container_name: bot_trading_prod
    restart: always
    environment:
      - DB_HOST=postgres_prod # Volvemos al NOMBRE, ahora sí va a funcionar
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    # Forzamos a que use ÚNICAMENTE esta red
    networks:
      - red_prod

networks:
  red_prod:
    external: true
    name: telegram-bot_default # El nombre que vimos en tu 'docker network ls'
